# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

# Security branch configuration
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        # 1111 in bcrypt/12
                        password: $2y$12$/KU6L3HUd2V4ISd.4MN8be9Ya3jR.FrqiPz.z6Rez8eUYTh2pCqQy
                        roles: 'ROLE_ADMIN'
                    vincent:
                        # 1111 in bcrypt/12
                        password: $2y$12$/KU6L3HUd2V4ISd.4MN8be9Ya3jR.FrqiPz.z6Rez8eUYTh2pCqQy
                        roles: 'ROLE_USER'
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
    encoders:
        Symfony\Component\Security\Core\User\UserInterface :
            algorithm: bcrypt
            cost: 12
        AppBundle\User :
            algorithm: bcrypt
            cost: 12

    firewalls:
        
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    
        main:
            provider: our_db_provider 
            # users_in_memory
            # our_db_provider
            anonymous: ~
            # activate different ways to authenticate
            logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            logout:
                path: /logout
                target: /
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: '^/users', roles: ROLE_ADMIN }
        - { path: '^/serviceinfo', roles: ROLE_USER }